### ISSUE TITLE
Pandas-4 and -5 have the same buggy & fixed commit IDs

### ISSUE THREAD

**Issue by satbekmyrza** [soarsmu/BugsInPy#44]
Pandas-4 and Pandas-5 have the same buggy and fixed commit IDs. 
Running a test for Pandas-4 works fine. However, running a test for Pandas-5 results in the following error:

`ERROR: not found: pandas/tests/groupby/test_function.py::test_ops_not_as_index`

**Comment by ratnadiraw** [comment]
Hi Satbek, thank you for the comment! We have updated the Pandas-5 commit ids.
