### ISSUE TITLE
Checking out buggy and fixed version of "scrapy 26" yields the same code

### ISSUE THREAD

**Issue by michaelpradel** [soarsmu/BugsInPy#82]
Steps to reproduce:
```
$ bugsinpy-checkout -p scrapy -i 26 -v 0 -w /tmp/buggy
$ bugsinpy-checkout -p scrapy -i 26 -v 1 -w /tmp/fixed
$ diff -r --exclude=".git" /tmp/buggy/ /tmp/fixed/
```
The `diff` command shows no difference, which doesn't seem to be the intended behavior. Is this a bug in BugsInPy, or am I missing something?

**Comment by ratnadiraw** [comment]
Hi Michael, thank you for highlighting the issue! We have updated the bugsinpy-checkout.
![image](https://github.com/soarsmu/BugsInPy/assets/15954561/c294b4e3-0344-4f19-aa49-98a9c55736a7)

**Comment by michaelpradel** [comment]
Great, thanks!
